# Generated by Django 4.0.3 on 2022-04-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Ціна')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубліковано')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Зображення')),
            ],
        ),
    ]
